version: '3'
services:
    web:
        image: nginx:alpine
        volumes:
            - "/opt/leacher/etc/nginx/default.conf:/etc/nginx/conf.d/default.conf"
            - "/opt/leacher/etc/ssl:/etc/ssl"
            - "/opt/leacher/web:/var/www/html"
            - "/opt/leacher/etc/nginx/default.template.conf:/etc/nginx/conf.d/default.template"
        ports:
            - "8000:80"
            - "3000:443"
        environment:
            - NGINX_HOST=${NGINX_HOST}
        command: /bin/sh -c "envsubst '$$NGINX_HOST' < /etc/nginx/conf.d/default.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
        restart: always
        depends_on:
            - php
            - mysqldb
    php:
        image: nanoninja/php-fpm:${PHP_VERSION}
        restart: always
        volumes:
            - "/opt/leacher/etc/php/php.ini:/usr/local/etc/php/conf.d/php.ini"
            - "/opt/leacher/web:/var/www/html"
    composer:
        image: "composer"
        volumes:
            - "/opt/leacher/web/app:/app"
        command: install
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - "/opt/leacher/.env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        ports:
            - "8989:3306"
        volumes:
            - "/opt/leacher/data/db/mysql:/var/lib/mysql"